#!/usr/bin/env Rscript

# Generate figures/FIGURE_INDEX.md: which of the files in figures/ a reader
# should run, which one renders the canonical panels, and which belong to a
# superseded generation that is kept so the frozen figures stay reproducible.
#
# Nothing here renames or rewrites a renderer. The generations are real history
# and all of them still run; what was missing was a single place that says
# which is current.
#
# Authority: provenance/publication_registry/figure_canonical_generation_registry.csv
# (figure_id, canonical_generation, canonical_renderer, manuscript_entry_point)
# and canonical_publication_registry.csv for the Extended Data identities.
# This tool only reformats those records; it never decides which is canonical.

source(file.path("R", "paths.R"))

gen_registry <- utils::read.csv(
  repo_path("provenance/publication_registry/figure_canonical_generation_registry.csv"),
  stringsAsFactors = FALSE)
pub_registry <- utils::read.csv(
  repo_path("provenance/publication_registry/canonical_publication_registry.csv"),
  stringsAsFactors = FALSE)

# The generation each filename prefix belongs to. Explicit, so a new generation
# has to be declared rather than guessed at.
GENERATIONS <- c(
  "final_truth_v9"  = "final_truth_v9",
  "editorial_v8"    = "editorial_v8",
  "nature_final_v7" = "nature_final_v7",
  "spatial_v6"      = "spatial_v6",
  "story_v5"        = "story_v5",
  "story_v4"        = "story_v4",
  "story_v3"        = "story_v3",
  "nature_v2"       = "nature_v2",
  "candidate"       = "candidate"
)

files <- sort(list.files(repo_path("figures"), pattern = "[.]R$"))
contracts <- sort(list.files(repo_path("figures"), pattern = "[.]ya?ml$"))

entry_points <- gen_registry$manuscript_entry_point
canonical_renderers <- gen_registry$canonical_renderer
canonical_gens <- unique(gen_registry$canonical_generation)
canonical_gens <- canonical_gens[canonical_gens %in% GENERATIONS]

generation_of <- function(nm) {
  for (p in names(GENERATIONS)) if (startsWith(nm, p)) return(GENERATIONS[[p]])
  NA_character_
}

rows <- lapply(files, function(nm) {
  rel <- paste0("figures/", nm)
  gen <- generation_of(nm)
  role <- if (rel %in% entry_points) {
    "MANUSCRIPT_ENTRY_POINT"
  } else if (rel %in% canonical_renderers) {
    "CANONICAL_RENDERER"
  } else if (!is.na(gen) && gen %in% canonical_gens) {
    "CANONICAL_GENERATION_SUPPORT"
  } else if (!is.na(gen)) {
    "SUPERSEDED_GENERATION"
  } else {
    "SHARED_SUPPORT"
  }
  data.frame(file = rel, generation = if (is.na(gen)) "-" else gen,
             role = role, stringsAsFactors = FALSE)
})
idx <- do.call(rbind, rows)

ORDER <- c("MANUSCRIPT_ENTRY_POINT", "CANONICAL_RENDERER",
           "CANONICAL_GENERATION_SUPPORT", "SHARED_SUPPORT",
           "SUPERSEDED_GENERATION")
idx$role <- factor(idx$role, levels = ORDER)
idx <- idx[order(idx$role, idx$file), ]

L <- c(
  "# Figure index",
  "",
  "Generated by `tools/generate_figure_index.R`. Do not hand-edit.",
  "",
  paste("`figures/` holds every figure generation this manuscript has passed",
        "through. All of them still run, deliberately, so the frozen figures",
        "stay reproducible. This index says which one is current."),
  "",
  "## Run these",
  "",
  "| Figure | Entry point | Canonical generation | Canonical renderer | Panels |",
  "| --- | --- | --- | --- | --- |")
for (i in seq_len(nrow(gen_registry))) {
  g <- gen_registry[i, ]
  L <- c(L, sprintf("| %s | `%s` | %s | `%s` | %s |",
                    g$figure_id, g$manuscript_entry_point,
                    g$canonical_generation, g$canonical_renderer, g$panels))
}
L <- c(L, "",
  paste("The **entry point** is what you run: it selects and validates the",
        "promoted artefact and assembles the figure. The **canonical",
        "renderer** is what produced the panels. They are different files on",
        "purpose; do not run a renderer expecting an assembled figure."),
  "")

ed <- pub_registry[grepl("^extended_data", pub_registry$publication_id), ]
if (nrow(ed)) {
  L <- c(L, "## Extended Data", "",
    "| Identity | Renderer | Status |", "| --- | --- | --- |")
  for (i in seq_len(nrow(ed))) {
    L <- c(L, sprintf("| %s | `%s` | %s |", ed$publication_id[i],
                      ed$canonical_renderer[i], ed$status[i]))
  }
  L <- c(L, "")
}

L <- c(L, "## Every file in `figures/`", "",
  "| File | Generation | Role |", "| --- | --- | --- |")
for (i in seq_len(nrow(idx))) {
  L <- c(L, sprintf("| `%s` | %s | %s |", idx$file[i], idx$generation[i],
                    as.character(idx$role[i])))
}
L <- c(L, "",
  "## Panel contracts", "",
  paste("One contract per generation. The contract for the canonical",
        "generation is the authority for panel identity, producer, inputs,",
        "scientific contract, biological unit, hemisphere handling and",
        "assembly position."),
  "",
  paste0("- `figures/", contracts, "`"),
  "")

writeLines(L, repo_path("figures", "FIGURE_INDEX.md"), useBytes = TRUE)
utils::write.csv(idx, repo_path("figures", "figure_index.csv"), row.names = FALSE)

cat("wrote figures/FIGURE_INDEX.md and figures/figure_index.csv\n")
cat("renderer files indexed  :", nrow(idx), "\n")
cat("panel contracts         :", length(contracts), "\n")
print(table(idx$role))
cat("\nfiles with no declared generation:",
    sum(idx$generation == "-"), "\n")
